### ISSUE TITLE
Chore/ Improve home page SEO

### ISSUE THREAD

**Issue by PetromirDev** [PetromirDev/safe-hawk#29]
![image](https://github.com/user-attachments/assets/f577985f-f6fd-45b5-889e-805aeba259cf)
## Tasks:

- [ ] Improve the homepage in terms of content
- [ ] Update the page title and description
- [ ] Add schema
- [ ] List supported providers
